# Generated by Django 3.0.5 on 2020-04-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('neighborhood_name', models.CharField(max_length=50)),
                ('overall_score', models.IntegerField()),
                ('walkability_score', models.DecimalField(decimal_places=10, max_digits=13)),
                ('groceries_score', models.DecimalField(decimal_places=10, max_digits=13)),
                ('parks_score', models.DecimalField(decimal_places=10, max_digits=13)),
                ('errands_score', models.DecimalField(decimal_places=10, max_digits=13)),
                ('restaurants_bars_score', models.DecimalField(decimal_places=10, max_digits=13)),
                ('shopping_score', models.DecimalField(decimal_places=10, max_digits=13)),
                ('entertainment_scores', models.DecimalField(decimal_places=10, max_digits=13)),
                ('schools_scores', models.DecimalField(decimal_places=10, max_digits=13)),
                ('transit_scores', models.DecimalField(decimal_places=10, max_digits=13)),
                ('bike_scores', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
    ]
